Create NeuralNetwork
kambed/SISE pull request #16
Opened 2022-04-14 10:47 UTC by RadekBucki

2022-04-18 17:43 UTC, kambed requested changes

2022-04-18 17:43 UTC, kambed commented on task2/src/main/java/backend/layer/Layer.java
> +import java.lang.reflect.Array;
Unused imports

2022-04-18 17:43 UTC, kambed commented on task2/src/main/java/backend/layer/DuplicationNeuronLayer.java
> +            output[i] = neurons[i].getTotalNeuronExcitation(new double[]{input[i]});
just input as in sigmoidal

2022-04-18 17:43 UTC, kambed commented on task2/src/main/java/backend/NeuralNetwork.java
> +            numberOfNeuronsInHiddenLayer = (int) Math.ceil(Math.sqrt(layerNumberOfInputs * numberOfOutputs));
first hidden layer num of neurons is from user and later you count it? Its inconsistent i guess.

2022-04-18 17:44 UTC, kambed commented
I think it's hard to check if everything works for now, tests would be nice

2022-04-18 17:51 UTC, kambed commented on task2/src/main/java/backend/NeuralNetwork.java
> +            numberOfNeuronsInHiddenLayer = (int) Math.ceil(Math.sqrt(layerNumberOfInputs * numberOfOutputs));
neuronów w poszczególnych warstwach, które to parametry powinny być określane w momencie tworzenia sieci.
Exercise frament telling u that it should be given by the user

2022-04-18 17:52 UTC, kambed requested changes

2022-04-18 17:52 UTC, kambed commented on task2/src/main/java/backend/layer/DuplicationNeuronLayer.java
> +            neurons[i] = new Neuron(1, x -> x);
Neurony przetwarzające, czyli neurony ukryte i wyjściowe (ewentualne neurony wejściowe nie są zaliczane do neuronów przetwarzających) mają mieć charakter nieliniowy i wykorzystywać sigmoidalną funkcję aktywacji
This layer should also be not linear

2022-04-18 17:55 UTC, kambed commented
Program ma umożliwiać określenie, czy podczas obliczania pobudzenia neuronu (sumy ważonej jego wejść) neurony przetwarzające mają uwzględniać wartość wejścia obciążającego (ang. bias), czy też nie
This part is missing

2022-04-23 17:17 UTC, RadekBucki commented on task2/src/main/java/backend/layer/DuplicationNeuronLayer.java
> +            output[i] = neurons[i].getTotalNeuronExcitation(new double[]{input[i]});
Input layer neurons has only one input, so why?

2022-04-23 17:20 UTC, RadekBucki commented on task2/src/main/java/backend/NeuralNetwork.java
> +            numberOfNeuronsInHiddenLayer = (int) Math.ceil(Math.sqrt(layerNumberOfInputs * numberOfOutputs));
leftovers from the previous approach :(

2022-04-23 17:20 UTC, RadekBucki commented on task2/src/main/java/backend/layer/DuplicationNeuronLayer.java
> +            neurons[i] = new Neuron(1, x -> x);
:O

2022-04-23 17:23 UTC, RadekBucki commented on task2/src/main/java/backend/layer/DuplicationNeuronLayer.java
> +            neurons[i] = new Neuron(1, x -> x);
Wait, this layer is not linear, because of Neuron implementation with weight, only function of duplication layer is linear

2022-04-24 14:37 UTC, kambed commented on task2/src/main/java/backend/layer/DuplicationNeuronLayer.java
> +            output[i] = neurons[i].getTotalNeuronExcitation(new double[]{input[i]});
i mean the way of writeing this

2022-04-24 17:53 UTC, RadekBucki commented on task2/src/main/java/backend/layer/DuplicationNeuronLayer.java
> +            output[i] = neurons[i].getTotalNeuronExcitation(new double[]{input[i]});
But this metod `getTotalNeuronExcitation` want double array, not double

2022-04-28 09:54 UTC, kambed approved these changes

2022-04-28 09:54 UTC, merged