Teacher implemented
kambed/SISE pull request #19
Opened 2022-04-29 18:34 UTC by kambed

2022-04-30 12:45 UTC, RadekBucki requested changes
I think there will be some new comments after backtracking propagation alghoritm refactor, becase of readable

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/DuplicationNeuron.java
> +}
This removes weights from this type of Neuron, I think it's not correct

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/DuplicationNeuron.java
> +public class DuplicationNeuron extends Neuron{
Missing whitespace

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/NeuralNetwork.java
> +        return layersResult;
This methods should throwing exception while working time

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/Neuron.java
> +        this.freeExpression = 1;
I know that on the Rajesh film bias was 0, but we have some simplification here, because we haven't b_1 input and we just add bias to final result.
````return activationFunction.apply(totalNeuronExcitation + freeExpression);````

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/frontend/Main.java
> +        System.out.println(Arrays.toString(nn.calculateOutput(new double[]{0, 0, 0, 0})));
This should be in tests

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/test/NeuronTest.java
>              assertTrue(weight > -1.0);
If you change `<` to `<=` below, please cahnge also here

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/test/TeacherTest.java
> +        assertEquals(0.75136,results[0],0.01);
If you use 0.01 precission, expected result should has same number of decimal places

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/test/TeacherTest.java
> +}
Missing Ctrl + Alt + L

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +    private void backpropagationAlgorithm(double[] inputs, double[] expected_outputs) throws IllegalAccessException {
**1. This function is too long, it should be devided to smaller parts called from it.**
2. We use camel case, not MCU Expresso Librarties notation :D
```suggestion
    private void backpropagationAlgorithm(double[] inputs, double[] expectedOutputs) throws IllegalAccessException {
```

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +        }
For example his can be a separated function

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +            totalErrorDerivatives[i] = -(expected_outputs[i / numOfNeuronsInPreviousLayer] - outputs[i / numOfNeuronsInPreviousLayer]);
This can be extracted to variable `i / numOfNeuronsInPreviousLayer`, there is no reason to calculate it 4 times.

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +            totalNeuronOutputErrorDerivativesOfOutputLayer[i] = totalErrorDerivatives[numOfNeuronsInPreviousLayer * i] * neuronOutputErrorDerivatives[numOfNeuronsInPreviousLayer * i];
Same here there is no reason to calculate it 2 times.

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +                } else {
This can be moved before `for` which stared in line 61 to avoid too much nesting.

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +            outputs = neuralNetwork.getLayersResult()[neuralNetwork.getNumberOfHiddenLayers() - hLayer];
This index (`neuralNetwork.getNumberOfHiddenLayers() - hLayer`) repeat 3 times, it will be faster to use variable

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +            numOfNeuronsInPreviousLayer = neuralNetwork.getLayersResult()[neuralNetwork.getNumberOfHiddenLayers() - (hLayer + 1)].length;
Same here (`neuralNetwork.getNumberOfHiddenLayers() - (hLayer + 1)`) but 2 times

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +            for (int j = 0; j < layer.getNeuron(i).getWeights().length; j++) {
Same here this (`layer.getNeuron(i).getWeights().length`) can be calculated i-times, not `i+i*j*2` times

2022-04-30 12:45 UTC, RadekBucki commented on task2/src/main/test/TeacherTest.java
> +public class TeacherTest {
I think we need a test for more than one hidden layer, it will be usefull/required to task 3

2022-04-30 12:59 UTC, kambed commented on task2/src/main/java/backend/DuplicationNeuron.java
> +}
That was the intention (duplication layer does not change anything) (ewentualne neurony wejściowe nie są zaliczane do neuronów przetwarzających)

2022-04-30 13:04 UTC, kambed commented on task2/src/main/java/frontend/Main.java
> +        System.out.println(Arrays.toString(nn.calculateOutput(new double[]{0, 0, 0, 0})));
It's impossible to test this way (This was usage example so it could be removed now)

2022-04-30 13:04 UTC, kambed commented on task2/src/main/java/backend/Neuron.java
> +        this.freeExpression = 1;
It's changed in user interface letting you to choose if bais occurs

2022-04-30 13:05 UTC, RadekBucki commented on task2/src/main/java/backend/DuplicationNeuron.java
> +}
So in this case we can simplify it to 
```suggestion
package backend;

public class DuplicationNeuron extends Neuron {
    public DuplicationNeuron() {
        super(1, x -> x);
    }

    public Double getTotalNeuronExcitation(double input) {
        return input;
    }
}
```
or eaven remove input layer.

2022-04-30 13:26 UTC, kambed commented on task2/src/main/test/TeacherTest.java
> +public class TeacherTest {
Counting this without Rajesh would be time consuming and probably not worth it now

2022-04-30 14:03 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +    private void backpropagationAlgorithm(double[] inputs, double[] expected_outputs) throws IllegalAccessException {
First point is not resoved, Total error was only example

2022-04-30 14:06 UTC, RadekBucki commented on task2/src/main/java/backend/Neuron.java
> +        this.freeExpression = 1;
Ok, but, when it occurs, it should be select randomly, and when not, it should be probably 0, not 1

2022-04-30 15:32 UTC, kambed commented on task2/src/main/java/backend/Neuron.java
> +        this.freeExpression = 1;
It will be like that when gui will be ready

2022-04-30 16:37 UTC, RadekBucki requested changes

2022-04-30 16:37 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +        double totalError = calculateTotalError(outputs, expectedOutputs);
This is not used

2022-04-30 16:37 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +        double[] outputs = neuralNetwork.getLayersResult()[neuralNetwork.getNumberOfHiddenLayers() + 1];
Sometimes you use `neuralNetwork.getNumberOfHiddenLayers()` and sometimes `neuralNetwork.getHiddenLayers().length`, clariffy it.

2022-04-30 16:37 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +                layer.setLastWeightChange(j, (weightsError[i * layer.getNeuron(i).getWeights().length + j] * learingRate) + (momentumRate * layer.getLastWeightChange()[j]));
You have extracted this (`neuralNetwork.getHiddenLayers().length`) into numOfWeightInNeuron variable, don't calculate it again and weight change is calculated twicely.
```suggestion
                double weightChange = weightsError[i * numOfWeightInNeuron + j] * learingRate + momentumRate * layer.getLastWeightChange()[j];
                layer.getNeuron(i).setWeight(j, layer.getNeuron(i).getWeights()[j] - weightChange);
                layer.setLastWeightChange(j, weightChange);
```

2022-04-30 16:37 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +                    }
This can be extracted `neuralNetwork.getHiddenLayers().length - hLayer`

2022-04-30 16:37 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +                neuronErrorDerivatives[i] = neuralNetwork.getLayersResult()[neuralNetwork.getNumberOfHiddenLayers() - (hLayer + 1)][i % numOfNeuronsInPreviousLayer];
This (`neuralNetwork.getNumberOfHiddenLayers() - (hLayer + 1)`) repeats in line 95

2022-04-30 16:37 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +            double[] neuronErrorDerivatives = new double[numOfConnectionsInLayer];
Is the reason for declaring this arrays?
There is only one using of then in line 115 with i-th array element, so it's can be local variable in for with i iterable?

2022-05-01 09:59 UTC, kambed commented on task2/src/main/java/backend/Teacher.java
> +                layer.setLastWeightChange(j, (weightsError[i * layer.getNeuron(i).getWeights().length + j] * learingRate) + (momentumRate * layer.getLastWeightChange()[j]));
I changed it to getNumberOfHiddenLayers so problem does not occur any more.

2022-05-01 10:02 UTC, kambed commented on task2/src/main/java/backend/Teacher.java
> +            double[] neuronErrorDerivatives = new double[numOfConnectionsInLayer];
In output layer it is used to calculate sth but in hidden layers it could be removed.

2022-05-01 11:01 UTC, RadekBucki requested changes

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/java/backend/NeuralNetwork.java
> +            boolean withBais
typo `bias` here and down

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/java/backend/NeuralNetwork.java
> +        this(numberOfInputs, numberOfOutputs, 1, numberOfNeuronsInHiddenLayer, withBais);
Typo `bias`

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/java/backend/Neuron.java
> +            this.freeExpression = 1;
Bias should be random, not 1

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/java/backend/layer/SigmoidalNeuronLayer.java
> +    public SigmoidalNeuronLayer(int numberOfInputs, int numberOfNeurons, boolean withBais) {
Typo bias

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/java/frontend/Main.java
>  public class Main {
Missing of removal?

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/java/frontend/MainFormController.java
> +        if (!stringPath.equals("")) {
Here and down
```suggestion
        if (!stringPath.isBlank()) {
```

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/resources/frontend/MainForm.fxml
> +<Pane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="719.0" prefWidth="959.0" style="-fx-background-color: #000055;" xmlns="http://javafx.com/javafx
Ctrl+Alt+L?

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +                layer.setLastWeightChange(j, (weightsError[i * layer.getNeuron(i).getWeights().length + j] * learingRate) + (momentumRate * layer.getLastWeightChange()[j]));
Problem is still occur, this part `weightsError[i * layer.getNeuron(i).getWeights().length + j] * learingRate) + (momentumRate * layer.getLastWeightChange()[j])` repeats twicely and creates train in 2 lines

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +                    }
`neuralNetwork.getHiddenLayers()[hiddenLayerNum]` can be before for

2022-05-01 11:01 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +                        (1 - outputs[i / numOfNeuronsInPreviousLayer]);
`i / numOfNeuronsInPreviousLayer` can be extracted to the vatiable on the begin of the for. Repeats in line 99 too

2022-05-01 12:14 UTC, kambed commented on task2/src/main/java/frontend/Main.java
>  public class Main {
That's reserve gui, if you want cli it's possible that's why I left it.

2022-05-01 15:20 UTC, RadekBucki requested changes

2022-05-01 15:20 UTC, RadekBucki commented on task2/src/main/java/backend/NeuralNetwork.java
> +        this(numberOfInputs, numberOfOutputs, 1, numberOfNeuronsInHiddenLayer, withBais);
Not resolved :(

2022-05-01 15:20 UTC, RadekBucki commented on task2/src/main/java/backend/NeuralNetwork.java
> +            boolean withBais
Not resolved :(

2022-05-01 15:20 UTC, RadekBucki commented on task2/src/main/java/backend/NeuralNetwork.java
> +        outputLayer = new SigmoidalNeuronLayer(numberOfNeuronsInHiddenLayer, numberOfOutputs, withBais);
Here typo too, please use ctrl+shift+R, not change in one place and ignore rest...

2022-05-01 15:20 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +    private double learingRate;
Typo learningRate

2022-05-01 15:20 UTC, RadekBucki commented on task2/src/main/java/backend/Teacher.java
> +    public Teacher(NeuralNetwork neuralNetwork, double learingRate, double momentumRate) {
Typo learningRate

2022-05-01 15:29 UTC, kambed commented on task2/src/main/java/backend/NeuralNetwork.java
> +        outputLayer = new SigmoidalNeuronLayer(numberOfNeuronsInHiddenLayer, numberOfOutputs, withBais);
I used it but it was uused in like 10 places :D

2022-05-01 16:26 UTC, RadekBucki approved these changes
Acceptable

2022-05-01 16:27 UTC, merged